spring:
  config:
    import: configserver:http://localhost:10332
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      label: main
management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    db:
      enabled: false
    redis:
      enabled: false

server:
  tomcat:
    max-part-count: 30